#!/bin/sh

echo 'OK Pleased to meet you'

while read stdin; do
	case $stdin in
		*BYE*) break ;;
		*SETDESC*) KEYNAME=${stdin#*:%0A%22}; KEYNAME=${KEYNAME%\%22\%0A*}; KEYID=${stdin#*ID }; KEYID=${KEYID%,*}; echo OK ;;
		*GETPIN*) echo "D `DISPLAY=:0 printf "" | tofi --require-match false --ascii-input false --hide-input true --prompt-text "gpg-agent - $KEYNAME ($KEYID): "`\nOK" ;;
		*) echo OK
	esac
done
